name: Run Tests
on:
  push:
    branches:
      - 'main'
      - 'feature/*'
  schedule:
    # may have to adjust this schedule, but mostly charts to start with
    - cron: '0 13 * * 5'

env:
  DISCORD_WEBHOOK: " "
  DB_NAME: ${{ secrets.PSCALE_DB_NAME }}
  DB_USER: ${{ secrets.PSCALE_DB_USER }}
  DB_HOST: ${{ secrets.PSCALE_DB_HOST }}
  DB_PASSWORD: ${{ secrets.PSCALE_DB_PASSWORD }}
  REMOTE_SELENIUM_URL: ${{ secrets.REMOTE_SELENIUM_URL }}
  MAX_ITERATIONS: 1
  # DB_NAME: streaming_audio_test
  # DB_USER: gh_actions
  # DB_HOST: 127.0.0.1
  # DB_PASSWORD: password

# Add cron job to ensure external webpages + apis have no changed
jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: coverage
    env:
      PYTHON: 3.8
      OS: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8.1

      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements/requirements.txt
          python -m pip install -r requirements/requirements.dev.txt
          python -m pip install -r requirements/requirements.livestream.txt

      - name: Coverage Report
        run:  |
          python -m coverage run -m unittest discover

      - name: Output Coverage
        run: |
          python -m coverage report
          python -m coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: coverage.xml
          flags: streaming_audio
          env_vars: PYTHON,OS
          fail_ci_if_error: true
