# transcribe video from url on demand
name: transcribe_video
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Url to dropbox'     
        required: false
        default: 'https://www.dropbox.com/s/jvajeen28clpicy/archive.mp4?dl=1' 
    paths-ignore:
      - "*.md"
      - "*.txt"

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_LIVESTREAM_WEBHOOK }}

jobs:
  scrap_data:
    runs-on: ubuntu-latest
    name: transcribe video
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.4' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements/requirements.txt
          python seed.py
      - uses: FedericoCarboni/setup-ffmpeg@v1
        # same as GITHUB_WORKSPACE 
        id: setup-ffmpeg

      - name: Where are files?
        run: ls
      

      - name: Transcribe with url
        if: "${{ github.event.inputs.url != '' }}"
        run: python transcribe_video.py --url "${{ github.event.inputs.url }}"

      # upload *.json file
      - name: Upload json file
        uses: actions/upload-artifact@v2
        with:
          name: transcribed_json
          path: video.json

