# produce yaml file cron job
name: Transcribe video
on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'Url to youtube video'     
        required: true
        default: 'warning' 
  push:
    branches:
      - 'main'
      - "feature/*"
    paths-ignore:
      - "*.md"
      - "*.txt"

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_LIVESTREAM_WEBHOOK }}
  WIT_AI_TOKEN: ${{ secrets.WIT_AI_TOKEN }}
# Add cron job to ensure external webpages + apis have no changed

jobs:
  scrap_data:
    runs-on: ubuntu-latest
    name: transcribe video

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - name: Transcribe with url
        if: "${{ github.event.inputs.youtube_url != '' }}"
        run: python transcript_manager.py --url "${{ github.event.inputs.youtube_url }}"

      # for master/main only use
      - name: Transcribe without url
        if: "${{ github.event.inputs.level == '' }}"
        run: python transcript_manager.py
        
      - name: Commit files
        run: |
          if [[ -z $(git status -s) ]]
          then
            echo "tree is clean"
          else
            git add . || true
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            echo "tree is dirty, please commit changes before running this"
            echo "PUSH_FILES=true" >> $GITHUB_ENV
            git config pull.rebase false || true
            git commit -m "Add changes" -a
            git merge -Xours main || true
            git pull origin main --strategy=ours || true
            git pull origin main || true
          fi
      - name: Test
        run: echo ${{ env.PUSH_FILES }}

      - name: Push changes
        if: ${{ env.PUSH_FILES == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}